DROP TABLE users IF EXISTS;

CREATE TABLE users (
id INT NOT NULL PRIMARY KEY,
username VARCHAR(45) NOT NULL,
password TEXT NOT NULL,
algorithm VARCHAR(45) NOT NULL
);

DROP TABLE authorities IF EXISTS;

CREATE TABLE authorities (
id INT NOT NULL PRIMARY KEY,
name VARCHAR(45) NOT NULL,
user INT
);

DROP TABLE PRODUCTS IF EXISTS;

CREATE TABLE PRODUCTS (
id INT NOT NULL PRIMARY KEY,
name VARCHAR(45) NOT NULL,
price VARCHAR(45) NOT NULL,
currency VARCHAR(45) NOT NULL
);

